# Generated by Django 6.0 on 2025-12-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='User', max_length=100),
            preserve_default=False,
        ),
    ]
